blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index,name='index'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('blog/type<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
]

byb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'),name = 'index'),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('login',include('login_register.urls')),
]
urlpatterns += static('/media/',document_root = settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('update_comment/',views.update_comment,name = 'update_comment'),

]

login_register/urls.py
from django.urls import path
from . import views

app_name = 'lisd'

urlpatterns = [
    # 登录登出
    path('login/', views.login_html, name='login'),
    path('signin_login/', views.signin_login, name='signin_login'),
    path('login_out/', views.login_out, name='login_out'),
    # 注册
    path('register/', views.register, name='register'),
    path('register_submit/', views.register_submit, name='register_submit'),
    # 修改密码
    path('change/', views.change_password, name='change_name'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import SmallIntegerField
from ckeditor_uploader.fields import RichTextUploadingField
from read_count.models import ReadNumExpandMethod


class Lunbo(models.Model):
    IS_CHOOES = (
        (1,'显示到主页'),
        (0,'不显示到主页')
    )
    img = models.ImageField(upload_to="blog", verbose_name='上传图片')
    text = RichTextUploadingField(verbose_name='图片文字',default=' ')
    chooes = SmallIntegerField(choices=IS_CHOOES, verbose_name='图片是否显示在主页')

    class Meta:
        verbose_name = '主页图片展示'
        verbose_name_plural = verbose_name


class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name


class Blog(models.Model,ReadNumExpandMethod):
    title = models.CharField(max_length=50)
    blog_type = models.ForeignKey(BlogType, on_delete=models.DO_NOTHING)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    create_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)



    def __str__(self):
        return "<Blog:%s>" % self.title

    class Meta:
        ordering = ['-create_time']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Lunbo,Blog,BlogType
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from read_count.utils import read_count_once_read
from comment.models import Comment


each_page_blogs_number = 5


def index(request):
    img_list = Lunbo.objects.filter(chooes=1).order_by('id')
    imgs_list = []
    img_index = []
    for i in img_list:
        if i.chooes==1:
            imgs_list.append(i)
            set(imgs_list)
            list(imgs_list)
    for k,v in enumerate(imgs_list):
        img_index.append(k)

    context ={}
    context['img_list'] = img_list
    context['img_index'] = img_index
    return render(request, 'blog/index.html', context)

def blog_list(request):

    blogs_all_list = Blog.objects.all()
    paginator = Paginator(blogs_all_list,settings.EACH_PAGE_BLOGS_NUMBER)# 每五篇为一页
    page_num = request.GET.get('page', 1)# 获取url的页面参数（get请求）
    page_of_blogs = paginator.get_page(page_num)
    current_page_num = page_of_blogs.number # 获取当前页码
    # 获取当前页码前后各两页的页码范围
    page_range = list(range(max(current_page_num - 2,1),current_page_num)) + list(range(current_page_num,min(current_page_num + 2,paginator.num_pages) + 1))
    if page_range[0] - 1 >= 2:
        page_range.insert(0,"...")
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append("...")
    # 加首页和尾页
    if page_range[0] != 1:
        page_range.insert(0,1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    context = {}
    context['blogs'] = page_of_blogs.object_list
    context['page_of_blogs'] = page_of_blogs
    context['page_range'] = page_range
    context['blog_types'] = BlogType.objects.all()
    return render(request,'blog/blog_list.html',context)


def blog_detail(request, blog_pk):
    blog = get_object_or_404(Blog, pk=blog_pk)
    read_cookie_key = read_count_once_read(request,blog)
    blog_content_type = ContentType.objects.get_for_model(blog)
    comments = Comment.objects.filter(content_type = blog_content_type,object_id=blog.pk)

    context = {}
    context['previous_blog'] = Blog.objects.filter(create_time__gt=blog.create_time).last()
    context['next_blog'] = Blog.objects.filter(create_time__lt=blog.create_time).first()
    context['blog'] = blog
    context['user'] = request.user
    context['comments'] = comments
    response = render(request,'blog/blog_detail.html',context)
    response.set_cookie(read_cookie_key,'true')
    return response


def blogs_with_type(request,blog_type_pk):
    context = {}
    blog_type = get_object_or_404(BlogType,pk=blog_type_pk)

    blogs_all_list = Blog.objects.filter(blog_type=blog_type)
    paginator = Paginator(blogs_all_list, settings.EACH_PAGE_BLOGS_NUMBER)  # 每五篇为一页
    page_num = request.GET.get('page', 1)
    page_of_blogs = paginator.get_page(page_num)
    current_page_num = page_of_blogs.number
    page_range = list(range(max(current_page_num - 2, 1), current_page_num)) + list(
        range(current_page_num, min(current_page_num + 2, paginator.num_pages) + 1))
    if page_range[0] - 1 >= 2:
        page_range.insert(0, "...")
    if paginator.num_pages - 1 >= 2:
        page_range.append("...")
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    context = {}
    context['blog_type']= blog_type

    context['blogs'] = page_of_blogs.object_list
    context['page_of_blogs'] = page_of_blogs
    context['page_range'] = page_range
    context['blog_types'] = BlogType.objects.all()

    return render(request,'blog/blogs_with_type.html',context)

blog/templates/blog/blog_detail.html
{% extends 'blog/index.html' %}

{% block title %}
    {{ block.title }}
{% endblock %}

{% load static %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title }}</h3>
                <ul class="blog-info-description">
                    <li>作者：{{ blog.author }}</li>
                    <li>分类：<a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a></li>
                    <li>发表日期：{{ blog.create_time|date:"Y-m-d" }}</li>
                    <li>阅读（{{ blog.get_read_num }}）</li>
                </ul>
                <span class="blog_contant">
                    {{ blog.content|safe }}
                </span>
                <div aria-label="..." class="pager_pre_next">
                    <ul class="pager">
                        <li class="previous">
                            {% if previous_blog %}
                                <a href="{% url 'blog:blog_detail' previous_blog.pk %}">
                                    <span aria-hidden="true"></span>
                                    上一篇：{{ previous_blog.title }}
                                </a>
                            {% endif %}
                        </li>
                        <li class="next">
                            {% if next_blog %}
                                <a href="{% url 'blog:blog_detail' next_blog.pk %}">
                                    下一篇：{{ next_blog.title }}
                                    <span aria-hidden="true"></span>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment-area">
                    <h3 class="comment-area-title">
                        评论
                    </h3>
                    {% if user and user.is_authenticated %}
                        已登录，{{ user }}<a href="{% url 'lisd:login_out' %}">退出登录</a>
                        <textarea id="comment_text" name="comment_text" cols="30" rows="10"></textarea>
                        <input type="hidden" name="object_id" id="object_id" value="{{ blog.pk }}">
                        <input type="hidden" name="content_type" id="content_type" value="blog">
                        <input type="submit" id="comment" value="评论">
                    {% else %}
                        登录才可评论 <a href="{% url 'lisd:login' %}">登录</a>
                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">评论列表</h3>
                    {% for comment in comments %}
                        <div>
                            {{ comment.user }}
                            ({{ comment.comment_time | date:"Y-m-d H:n:s"}}):
                            {{ comment.text }}
                        </div>
                    {% empty %}
                        暂无评论
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        // 页面加载完成
        $(function(){
            $("#comment").click(function(){
                $.ajax({
                // 访问的目标url
                url:"{% url 'comment:update_comment' %}",
                // http的method
                type: "POST",
                // 提交的参数
                data: { "comment_text":$("#comment_text").val(),
                    'object_id': $("#object_id").val(),
                    'content_type':$("#content_type").val()},
                // 后台返回成功后，调用的回调函数
                success: function (data) {

                    if (data['err']==1){
                        $("#comment_text").val('');
                        $(location).attr('href',"{% url 'blog:blog_detail' blog.pk %}");
                    }
                    else if (data['err']==0){
                        alert(data['msg']);
                        $("#comment_text").val('');
                    }

                    {#alert(data + "123");#}
                    {#// 阻止this的默认行为#}
                    {#this.preventDefault();#}
                },
                // 服务器返回错误
                error: function () {
                    alert('error');
                }
                });
            });
        });
    </script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/index.html' %}
{% load static %}

{% block title %}
    我的网站
{% endblock %}


{% block head_er %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block blog_list_title %}<h4>博客列表</h4>{% endblock %}
                    </div>
                    <div class="panel-body">
                        {% for blog in blogs %}
                            <div class="blog">
                                <a href="{% url 'blog:blog_detail' blog.pk %}">
                                    <h3>{{ blog.title }}</h3>
                                </a>
                                <p class="blog-info">
                                    <span class="glyphicon glyphicon-tag"></span>&nbsp;&nbsp;<a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>&nbsp;&nbsp;&nbsp;
                                    <span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;发表日期：{{ blog.create_time|date:"Y-m-d H:n:s" }}
                                    &nbsp;&nbsp;&nbsp;阅读（{{ blog.get_read_num }}）
                                </p>
                                <p class="blog_contant">
                                    {{ blog.content|striptags|truncatechars:120 }}
                                </p>
                            </div>
                        {% empty %}
                            <div class="blog">
                                <h3>暂无博客，敬请期待</h3>
                            </div>
                        {% endfor %}

                    </div>
                </div>
                <div aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            {% if page_of_blogs.has_previous %}
                                <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                 <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                            {% endif %}
                        </li>
                            {% for page_num in page_range %}

                                {% if page_num == page_of_blogs.number %}
                                    <li class="active"><span>{{ page_num }}</span></li>
                                {% else %}
                                    {% if page_num == "..." %}
                                        <li class="disabled"><span>{{ page_num }}</span></li>
                                    {% else %}
                                        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        <li>
                            {% if page_of_blogs.has_next %}
                                <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                <li class="disabled"><a href="#" aria-label="Next"><span aria-hidden="true">&laquo;</span></a></li>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="clear"></div>
                <p class="blog_page_foot">共有{{ page_of_blogs.paginator.count }}篇博客&nbsp;&nbsp;&nbsp;当前第{{ page_of_blogs.number }}页&nbsp;&nbsp;&nbsp;共有{{ page_of_blogs.paginator.num_pages }}页</p>
            </div>
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>
                            博客分类
                        </h4>
                    </div>
                    <div class="panel-body">
                        <ul>
                            {% for blog_type in blog_types %}
                                <li class="li_type"><a href="{% url 'blog:blogs_with_type' blog_type.pk %}">{{ blog_type.type_name }}</a></li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/APlayer.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    {% block head_er %}{% endblock %}
</head>
<body>
    <div class="logo">
        <img src="{% static 'img/logo.jpg' %}" alt="">
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="/">首页</a></li>
                    <li><a href="{% url 'blog:blog_list' %}">博客</a></li>
                    <li><a href="{% url 'lisd:login' %}">登录</a></li>
                    <li><a href="#">...</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for i in img_index %}
                    {% if forloop.counter0 == 0 %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ i }}" class="active"></li>
                    {% else %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ i }}"></li>
                    {% endif %}
                {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
                {% for i in img_list %}
                    {% if forloop.counter0 == 0 %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                        <img src="{{ i.img.url }}" alt="">
                        <div class="carousel-caption">
                            {{ i.text|safe }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="row" id="row">
            <div class="row_row">
                <div class="col-xs-4 col-md-2">
                    <a href="#" class="thumbnail">
                    <img src="{% static 'img/b1.jpg' %}" alt="...">
                    </a>
                </div>
                <div class="col-xs-4 col-md-2">
                    <a href="#" class="thumbnail">
                    <img src="{% static 'img/b1.jpg' %}" alt="...">
                    </a>
                </div>
                <div class="col-xs-4 col-md-2">
                    <a href="#" class="thumbnail">
                    <img src="{% static 'img/b1.jpg' %}" alt="...">
                    </a>
                </div>
                <div class="col-xs-4 col-md-2">
                    <a href="#" class="thumbnail">
                    <img src="{% static 'img/b1.jpg' %}" alt="...">
                    </a>
                </div>
                <div class="col-xs-4 col-md-2">
                    <a href="#" class="thumbnail">
                    <img src="{% static 'img/b1.jpg' %}" alt="...">
                    </a>
                </div>
            </div>

        </div>
    {% endblock %}
    <div class="play">
        <div id="aplayer"></div>
    </div>
</body>
    <script type="text/javascript" src="{% static 'js/APlayer.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</html>

blog/templates/blog/register.html
{% extends 'blog/index.html' %}
{% load static %}
{% block head_er %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//Custom Theme files -->
<!--js-->
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<!--//js-->
<!--cart-->
<script src="{% static 'js/simpleCart.min.js' %}"></script>
<!--cart-->
<!--web-fonts-->
<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Fascinate' rel='stylesheet' type='text/css'>
<!--web-fonts-->
<!--animation-effect-->
<link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
<script src="{% static 'js/wow.min.js' %}"></script>
	<script>
	 new WOW().init();
	</script>
<!--//animation-effect-->
<!--start-smooth-scrolling-->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
</script>
{% endblock %}
{% block content %}

	<!--breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>主页</a></li>
				<li class="active">注册</li>
			</ol>
		</div>
	</div>
	<!--//breadcrumbs-->
	<!--login-->
	<div class="login-page">
		<div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
			<h3 class="title">注册<span> Form</span></h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit curabitur </p>
		</div>
		<div class="widget-shadow">
			<div class="login-top wow fadeInUp animated" data-wow-delay=".7s">
				<h4>已有账号 ?<a href="{% url 'lisd:login' %}">  直接登录 »</a> </h4>
			</div>
			<div class="login-body">
{#				<form class="wow fadeInUp animated" data-wow-delay=".7s" action="{% url 'lisd:register_submit' %}" method="post">#}
					<input type="text" name="username" id="username" placeholder="请输入用户名" required="">
					<input type="password" name="password1" id="password1" class="lock" placeholder="请输入密码">
                    <input type="password" name="password2" id="password2" class="lock" placeholder="再一次输入密码">
                    <input type="submit" name="Register" id="register" value="注册">
{#				</form>#}
			</div>
		</div>
	</div>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        // 页面加载完成
        $(function(){
            $("#register").click(function(){
                $.ajax({
                // 访问的目标url
                url:"{% url 'lisd:register_submit' %}",
                // http的method
                type: "POST",
                // 提交的参数
                data: { "username":$("#username").val(),
                    'password1': $("#password1").val(),
                    'password2': $("#password2").val()},
                // 后台返回成功后，调用的回调函数
                success: function (data) {
                    if (data['err']==1) {
                        $("#username").val('');
                        $("#password1").val('');
                        $("#password2").val('');
                        alert(data['msg']);

                    }
                    else if (data['err']==0){
                        alert('注册成功..点击跳转至登录页面');
                        $(location).attr('href',"{% url 'lisd:login' %}");
                    }

                    {#if(err ==1){#}
                    {#    $("#username").val('');#}
                    {#    $("#password1").val('');#}
                    {#    $("#password2").val('');#}
                    {# }#}
                    {#else#}
                    {#    $(location).attr('href',"{% url 'lisd:login' %}");#}
                    {#alert(data + "123");#}
                    {#// 阻止this的默认行为#}
                    {#this.preventDefault();#}
                },
                // 服务器返回错误
                error: function () {
                    alert('error');
                }
                });
            });
        });
    </script>
	<!--//login-->
	<!--footer-->
{% endblock %}

blog/templates/blog/signin.html
{% extends 'blog/index.html' %}
{% load static %}
{% block head_er %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//Custom Theme files -->
<!--js-->
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<!--//js-->
<!--cart-->
<script src="{% static 'js/simpleCart.min.js' %}"></script>
<!--cart-->
<!--web-fonts-->
<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Fascinate' rel='stylesheet' type='text/css'>
<!--web-fonts-->
<!--animation-effect-->
<link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
<script src="{% static 'js/wow.min.js' %}"></script>
	<script>
	 new WOW().init();
	</script>
<!--//animation-effect-->
<!--start-smooth-scrolling-->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
</script>
{% endblock %}
{% block content %}
	<!--breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow fadeInUp" data-wow-delay=".5s">
				<li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>主页</a></li>
				<li class="active">登  录</li>
			</ol>
		</div>
	</div>
	<!--//breadcrumbs-->
	<!--login-->
	<div class="login-page">
		<div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
			<h3 class="title">登录<span> 表单</span></h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit curabitur </p>
		</div>
		<div class="widget-shadow">
			<div class="login-top wow fadeInUp animated" data-wow-delay=".7s">
				<h4>欢迎 ! <br> 没有账户 ? <a href="{% url 'lisd:register' %}">  现在就去注册 »</a> </h4>
			</div>
			<div class="login-body wow fadeInUp animated" data-wow-delay=".7s">
{#				<form action="{% url 'lisd:signin_login' %}" method="post">#}
					<input type="text" class="user" name="username" id="username" placeholder="输入您的用户名" required="">
					<input type="password" name="password" id="password" class="lock" placeholder="密码">
                    {% if error_message %}
                        {{ error_message }}
                    {% endif %}
					<input type="submit" name="Sign In" id="signin" value="登 录">
					<div class="forgot-grid">
						<label class="checkbox"><input type="checkbox" name="checkbox"><i></i>记住我</label>
{#						<div class="forgot">#}
{#							<a href="#">Forgot Password?</a>#}
{#						</div>#}
						<div class="clearfix"> </div>
					</div>
{#				</form>#}
			</div>
		</div>
	</div>
	<!--//login-->
	<!--footer-->
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        // 页面加载完成
        $(function(){
            $("#signin").click(function(){
                $.ajax({
                // 访问的目标url
                url:"{% url 'lisd:signin_login' %}",
                // http的method
                type: "POST",
                // 提交的参数
                data: { "username":$("#username").val(),
                    'password': $("#password").val()},
                // 后台返回成功后，调用的回调函数
                success: function (data) {
                    if (data['err']==1) {
                        $("#username").val('');
                        $("#password1").val('');
                        $("#password2").val('');
                        alert(data['msg']);

                    }
                    else if (data['err']==0){
                        alert('登录成功..点击跳转至主页');
                        $(location).attr('href',"/");
                    }
                    else if (data['next']==next)
                        $(location).attr('href',next);

                    {#alert(data + "123");#}
                    {#// 阻止this的默认行为#}
                    {#this.preventDefault();#}
                },
                // 服务器返回错误
                error: function () {
                    alert('error');
                }
                });
            });
        });
    </script>

{% endblock %}